name: CI

"on":
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Installing requirements
        run: pip install -r requirements.txt

      - name: Checking versions
        run: python3 --version && echo "CI works!"

      - name: Pytest starts
        run: pytest

      - name: Building a container
        run: docker build .
